databases:
  - name: ramensite_DB
    databaseName: ramensite_db
    user: ramensite
    region: singapore

services:
  - type: web
    name: ramensite
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://ramen_site_db_user:3aeNBpscRREpiFuyo08OZpbvLrzi4uJN@dpg-cmh39n7109ks739angig-a/ramen_site_db
        fromDatabase:
          name: ramensite_DB
          property: connectionString
      - key: 2b1f5da81cad02387c1e23ce732aeb5c
        sync: false

